### ISSUE TITLE
Configure ES dataset schema to prevent errors with different datapackage.jsons

### ISSUE THREAD

**Issue by rufuspollock** [datahq/metastore#10]
May have an issue around how ES index schema works - i think once you create with first doc it gets upset if same property has a different type. e.g. you have a data package with a path field as a string and then we get an array we'll have problems ...

Concrete example of this is with example topojson dataset which failed to process with:

```javascript=
elasticsearch.dump.to_index: elasticsearch.helpers.BulkIndexError:
('1 document(s) failed to index.', [{'index': {'_index': 'datasets_20170804_7fce9667', '_type': 'dataset', '_id': '0e9b59cd50f1884058c1aa242d71a228/vega-views-tutorial-topojson', 'status': 400, 
'error': {'type': 'mapper_parsing_exception',
  'reason': 'object mapping for [views.spec.data.format.parse] tried to parse field [parse] as object,
but found a concrete value'}}}])
```

**Comment by akariv** [comment]
This is more of an issue for the assembler (as it is responsible for indexing, not metastore).
Anyway, this is no longer an issue since https://github.com/datahq/assembler/commit/405fd2a6ab2721911af46eea3d0a738f9202b54b
