### ISSUE TITLE
After pushing dataset, there is no event for it

### ISSUE THREAD

**Issue by Mikanebu** [datahq/metastore#20]
Please, see http://api-testing.datahub.io/metastore/search/events?owner=%22Mikanebu%22
https://testing.datahub.io/Mikanebu/push-speed-9. 

Also, missing events from yesterday. See these datasets https://datahub.io/opendatafortaxjustice

**Comment by zelima** [comment]
FIXED. Was cause by not passing `EVENTS_ELASTICSEARCH_HOST` env variable to metastore. http://api-testing.datahub.io/metastore/search/events?owner=%22Mikanebu%22&timestamp=%222017-11-28%22
