### ISSUE TITLE
We have `unlisted` datasets which are listed in search page

### ISSUE THREAD

**Issue by Mikanebu** [datahq/metastore#26]
@Mikanebu commented on [Mon Jan 22 2018](https://github.com/datahq/frontend/issues/179)

We want to fix our search page, so it will not show `unlisted` datasets

## Acceptance criteria

* [ ] there is no more `unlisted` datasets in search page

## Tasks 

* [ ] do analysis 
* [ ] write failing test
* [ ] debug 

## Analysis

Please, try to search https://datahub.io/search?q=employment and you will see some `unlisted` datasets under `core` user

**Comment by zelima** [comment]
FIXED
