### ISSUE TITLE
Extra resource in response from metastore API

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/metastore#8]
When I query API (http://api-testing.datahub.io/metastore/search?q=%22co2-ppm%22), there is an extra resource included in all packages. It always comes last in the `resources` array and breaks our normalization script in the frontend:

```json=
{
  "name": "__datasets",
  "path": "nonexistent",
  "schema": {
  "fields": [
  ...
}
```

**Comment by akariv** [comment]
Fixed via https://github.com/datahq/assembler/commit/91f0dbc64255c9ae62a1e803c28004ce566d08e7
