### ISSUE TITLE
Bytes and rowcount are missing in response

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/metastore#9]
So when I hit http://api-testing.datahub.io/metastore/search?q=%22co2-ppm%22, I don't get bytes and rowcounts for the package and resources.

* `response.results[0].datapackage.datahub.stats.bytes|rowcounts` has value of 0
* `response.results[0].datapackage.resources[0].datahub.stats` is not defined

**Comment by akariv** [comment]
Fixed via https://github.com/datahq/assembler/commit/91f0dbc64255c9ae62a1e803c28004ce566d08e7
